version: '3.8'

services:
  db:
    image: postgres:15
    container_name: meowshop_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=meowshop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: meowshop_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/meowshop
    depends_on:
      - db
    volumes:
      - ./backend:/app
    restart: always

volumes:
  postgres_data:
